
# Singleton piece positions
generate_singles: false
piece_singles:
  K: true
  Q: true
  R: true
  B: true
  N: true
single_generate_style: "all" # "all", "random", "none"/""
number_of_singles: # of single positions to generate if using "random" style. Ignored otherwise.

# Force certain endgames to be included
used_fens:
  - "5k2/8/8/8/8/8/8/3KQ3 w - - 0 1" # KQvK

# Random generation settings
num_positions: 20 # Total number of positions to generate. Used fens are included in this count.
force_valid: true # if true, only generate valid positions
max_attempts: 5000 # max consecutive attempts to generate valid positions before giving up
max_pieces: 5 # max total pieces on board
endgames:
  - "KQvK"
  - "KRvK"
  - "KPvK"
  - "KBvK"
  - "KNvK"
